include:
  - project: "bkwi/beheer/infraops/ontwikkeltooling/gitlab-ci"
    file: "gitlab-ci-yml/maven-deploy.yml"

deploy-to-repository:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: on_success